module AvatarHelper
  def avatars
    avatars = %w(https://i.ibb.co/SQHfQCN/Avatar-75.jpg
    https://i.ibb.co/tYbw0LB/Avatar-1.jpg
    https://i.ibb.co/5RL202L/Avatar-2.jpg
    https://i.ibb.co/JdtNpy9/Avatar-3.jpg
    https://i.ibb.co/G0SmWZY/Avatar-4.jpg
    https://i.ibb.co/wWwxzQY/Avatar-5.jpg
    https://i.ibb.co/1sZJ5Yg/Avatar-6.jpg
    https://i.ibb.co/VWhxDd6/Avatar-7.jpg
    https://i.ibb.co/9VLNf3F/Avatar-8.jpg
    https://i.ibb.co/Z27pWZV/Avatar-9.jpg
    https://i.ibb.co/84y3hjw/Avatar-10.jpg
    https://i.ibb.co/mTzhkxv/Avatar-11.jpg
    https://i.ibb.co/d0TMhmF/Avatar-12.jpg
    https://i.ibb.co/PDPLSpr/Avatar-13.jpg
    https://i.ibb.co/bzhrfSR/Avatar-14.jpg
    https://i.ibb.co/G5mYt8z/Avatar-15.jpg
    https://i.ibb.co/FbWV8W3/Avatar-16.jpg
    https://i.ibb.co/HrcS26j/Avatar-17.jpg
    https://i.ibb.co/xJp36P1/Avatar-18.jpg
    https://i.ibb.co/f2pjZrN/Avatar-19.jpg
    https://i.ibb.co/BytCtrf/Avatar-20.jpg
    https://i.ibb.co/4pD1rGV/Avatar-21.jpg
    https://i.ibb.co/Sw5cr6C/Avatar-22.jpg
    https://i.ibb.co/59WTYzH/Avatar-23.jpg
    https://i.ibb.co/WFNfQXd/Avatar-24.jpg
    https://i.ibb.co/ftHMTBg/Avatar-25.jpg
    https://i.ibb.co/TctW9v2/Avatar-26.jpg
    https://i.ibb.co/D84DTkW/Avatar-27.jpg
    https://i.ibb.co/4RF6QyV/Avatar-28.jpg
    https://i.ibb.co/F4j3cSd/Avatar-29.jpg
    https://i.ibb.co/y5kMcqk/Avatar-30.jpg
    https://i.ibb.co/P43YHGJ/Avatar-31.jpg
    https://i.ibb.co/LxWpRQy/Avatar-32.jpg
    https://i.ibb.co/dW75pNP/Avatar-33.jpg
    https://i.ibb.co/4W94ZC2/Avatar-34.jpg
    https://i.ibb.co/pXfHDMX/Avatar-35.jpg
    https://i.ibb.co/z4XF5SL/Avatar-36.jpg
    https://i.ibb.co/KXXDTXR/Avatar-37.jpg
    https://i.ibb.co/pf5pGy9/Avatar-38.jpg
    https://i.ibb.co/DPFJ3P7/Avatar-39.jpg
    https://i.ibb.co/qyzjcPB/Avatar-40.jpg
    https://i.ibb.co/kmhJQvr/Avatar-41.jpg
    https://i.ibb.co/g4CbfR2/Avatar-42.jpg
    https://i.ibb.co/9bkMLH8/Avatar-43.jpg
    https://i.ibb.co/djPLfDC/Avatar-44.jpg
    https://i.ibb.co/Q6b9pJs/Avatar-45.jpg
    https://i.ibb.co/RvbjHbv/Avatar-46.jpg
    https://i.ibb.co/ZL0s8SK/Avatar-47.jpg
    https://i.ibb.co/ZJHHS0h/Avatar-48.jpg
    https://i.ibb.co/W072C56/Avatar-49.jpg
    https://i.ibb.co/GRcy9P9/Avatar-50.jpg
    https://i.ibb.co/mrpWYqc/Avatar-51.jpg
    https://i.ibb.co/C5x1JN6/Avatar-52.jpg
    https://i.ibb.co/bdKdYPY/Avatar-53.jpg
    https://i.ibb.co/h14dnh9/Avatar-54.jpg
    https://i.ibb.co/4fH8Skt/Avatar-55.jpg
    https://i.ibb.co/vkS38B8/Avatar-56.jpg
    https://i.ibb.co/mHwPmS4/Avatar-57.jpg
    https://i.ibb.co/nnhRSyz/Avatar-58.jpg
    https://i.ibb.co/chdcDVs/Avatar-59.jpg
    https://i.ibb.co/6JWpx08/Avatar-60.jpg
    https://i.ibb.co/XbPk93J/Avatar-61.jpg
    https://i.ibb.co/YbHfj6t/Avatar-62.jpg
    https://i.ibb.co/dpJk9hr/Avatar-63.jpg
    https://i.ibb.co/HFk9wgg/Avatar-64.jpg
    https://i.ibb.co/vcSw1S5/Avatar-65.jpg
    https://i.ibb.co/PCJFrfB/Avatar-66.jpg
    https://i.ibb.co/0cjDvPR/Avatar-67.jpg
    https://i.ibb.co/3kh669B/Avatar-68.jpg
    https://i.ibb.co/8XFyCcZ/Avatar-69.jpg
    https://i.ibb.co/qswcFyw/Avatar-70.jpg
    https://i.ibb.co/4Z0r4qm/Avatar-71.jpg
    https://i.ibb.co/gM2QJQw/Avatar-72.jpg
    https://i.ibb.co/tHdgKYx/Avatar-73.jpg
    https://i.ibb.co/WK818GG/Avatar-74.jpg
    https://i.ibb.co/2Y6HpNq/Avatar-78.jpg
    https://i.ibb.co/7QXG8GD/Avatar-76.jpg
    https://i.ibb.co/MpZCVbH/Avatar-77.jpg)
  end

end
